name: Create release
on:
  push:
    tags:
      - 'v*'

jobs:
  create-windows-installer:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: .
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: 17
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run packageReleaseMsi with Gradle Wrapper
      run: ./gradlew packageReleaseMsi
    - run: Compress-Archive -Path ./build/compose/binaries/main-release/msi/*.msi -DestinationPath "${{ github.workspace }}/souffleur_windows.zip"
    - name: Upload asset
      uses: actions/upload-artifact@v3
      with:
        path: "${{ github.workspace }}/souffleur_windows.zip"
        name: souffleur_windows.zip

  create-macos-installer:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: .
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: 17
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Setup keychain, certificates and passwords
      env: 
        MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
        MACOS_CERTIFICATE_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PASSWORD }}
      run: |
        echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
        security create-keychain -p ${{ secrets.KEYCHAIN_PASSWORD }} build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p ${{ secrets.KEYCHAIN_PASSWORD }} build.keychain
        security import certificate.p12 -k build.keychain -P $MACOS_CERTIFICATE_PASSWORD -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k ${{ secrets.KEYCHAIN_PASSWORD }} build.keychain
    - name: "Build and notarize release app bundle"
      env:
        PROD_MACOS_NOTARIZATION_APPLE_ID: ${{ secrets.PROD_MACOS_NOTARIZATION_APPLE_ID }}
        PROD_MACOS_NOTARIZATION_TEAM_ID: ${{ secrets.PROD_MACOS_NOTARIZATION_TEAM_ID }}
        PROD_MACOS_NOTARIZATION_PWD: ${{ secrets.PROD_MACOS_NOTARIZATION_PWD }}
      run: |
        security unlock-keychain -p ${{ secrets.KEYCHAIN_PASSWORD }} build.keychain
        xcrun notarytool store-credentials "notarytool-profile" --apple-id "$PROD_MACOS_NOTARIZATION_APPLE_ID" --team-id "$PROD_MACOS_NOTARIZATION_TEAM_ID" --password "$PROD_MACOS_NOTARIZATION_PWD"
        ./gradlew notarizeReleaseDmg
        ditto -c -k ./build/compose/binaries/main-release/dmg/Souffleur*.dmg souffleur_macos.zip
        echo `pwd`
    - name: Upload asset
      uses: actions/upload-artifact@v3
      with:
        path: /Users/runner/work/souffleur_server/souffleur_server/souffleur_macos.zip
        name: souffleur_macos.zip
        
  create-release:
    runs-on: macos-latest
    needs: [ create-windows-installer,  create-macos-installer]
    steps:
    - name: Download macOS zip
      uses: actions/download-artifact@v4.1.7
      with:
        name: souffleur_macos.zip
    - name: Download Windows zip
      uses: actions/download-artifact@v4.1.7
      with:
        name: souffleur_windows.zip
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "souffleur_macos.zip,souffleur_windows.zip"
